"""empty message

Revision ID: 071225b7736f
Revises: 0dfbb34bf935
Create Date: 2024-01-18 17:31:49.785325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '071225b7736f'
down_revision = '0dfbb34bf935'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarea_persona', schema=None) as batch_op:
        batch_op.alter_column('fecha_termino',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarea_persona', schema=None) as batch_op:
        batch_op.alter_column('fecha_termino',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
