"""empty message

Revision ID: 0dfbb34bf935
Revises: 7805b38f8589
Create Date: 2024-01-17 19:15:21.959523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dfbb34bf935'
down_revision = '7805b38f8589'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('direccion', schema=None) as batch_op:
        batch_op.alter_column('numero',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('depto_casa',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('direccion', schema=None) as batch_op:
        batch_op.alter_column('depto_casa',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('numero',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    # ### end Alembic commands ###
