"""empty message

Revision ID: 7805b38f8589
Revises: 460516ac14a7
Create Date: 2024-01-16 17:50:54.181147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7805b38f8589'
down_revision = '460516ac14a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gasto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monto_original', sa.Integer(), nullable=False))
        batch_op.drop_column('monto')

    with op.batch_alter_table('tarea_persona', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_id_unidad_id_persona_id_tarea', ['id_unidad', 'id_persona', 'id_tarea'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarea_persona', schema=None) as batch_op:
        batch_op.drop_constraint('uq_id_unidad_id_persona_id_tarea', type_='unique')

    with op.batch_alter_table('gasto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monto', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('monto_original')

    # ### end Alembic commands ###
